services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: teleservice-conformite
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  maildev:
    image: maildev/maildev:latest
    restart: always
    ports:
      - "1080:1080" # Web interface
      - "1025:1025" # SMTP server
    environment:
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025

volumes:
  pgdata:
